# Based on https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/Dockerfile
FROM krallin/ubuntu-tini:14.04

MAINTAINER Kenneth C. Arnold <kcarnold@alum.mit.edu>

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda3-4.1.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

ENV PATH /opt/conda/bin:$PATH

WORKDIR /root
CMD [ "/bin/bash" ]
